UT_ASSERT_EQ(ft_isspace('a'), isspace('a'));
UT_ASSERT_EQ(ft_isspace('a' + 0x100), isspace('a' + 0x100));
UT_ASSERT_EQ(ft_isspace('2'), isspace('2'));
UT_ASSERT_EQ(ft_isspace('Z'), isspace('Z'));
UT_ASSERT_EQ(ft_isspace('t'), isspace('t'));
UT_ASSERT_EQ(ft_isspace(0), isspace(0));
UT_ASSERT_EQ(ft_isspace(1), isspace(1));
UT_ASSERT_EQ(ft_isspace(9999), isspace(9999));
UT_ASSERT_EQ(ft_isspace('1'), isspace('1'));
UT_ASSERT_EQ(ft_isspace('2'), isspace('2'));
UT_ASSERT_EQ(ft_isspace('A'), isspace('A'));
UT_ASSERT_EQ(ft_isspace('Z'), isspace('Z'));
UT_ASSERT_EQ(ft_isspace(' '), isspace(' '));
UT_ASSERT_EQ(ft_isspace('%'), isspace('%'));
UT_ASSERT_EQ(ft_isspace('\t'), isspace('\t'));
UT_ASSERT_EQ(ft_isspace('\n'), isspace('\n'));
UT_ASSERT_EQ(ft_isspace('\v'), isspace('\v'));
UT_ASSERT_EQ(ft_isspace('\b'), isspace('\b'));
UT_ASSERT_EQ(ft_isspace(7), isspace(7));
