UT_ASSERT_EQ(ft_isupper('a'), isupper('a'));
UT_ASSERT_EQ(ft_isupper('a' + 0x100), isupper('a' + 0x100));
UT_ASSERT_EQ(ft_isupper('2'), isupper('2'));
UT_ASSERT_EQ(ft_isupper('Z'), isupper('Z'));
UT_ASSERT_EQ(ft_isupper('t'), isupper('t'));
UT_ASSERT_EQ(ft_isupper(0), isupper(0));
UT_ASSERT_EQ(ft_isupper(1), isupper(1));
UT_ASSERT_EQ(ft_isupper(9999), isupper(9999));
UT_ASSERT_EQ(ft_isupper('1'), isupper('1'));
UT_ASSERT_EQ(ft_isupper('2'), isupper('2'));
UT_ASSERT_EQ(ft_isupper('A'), isupper('A'));
UT_ASSERT_EQ(ft_isupper('Z'), isupper('Z'));
UT_ASSERT_EQ(ft_isupper(' '), isupper(' '));
UT_ASSERT_EQ(ft_isupper('%'), isupper('%'));
UT_ASSERT_EQ(ft_isupper('\t'), isupper('\t'));
UT_ASSERT_EQ(ft_isupper('\n'), isupper('\n'));
UT_ASSERT_EQ(ft_isupper('\v'), isupper('\v'));
UT_ASSERT_EQ(ft_isupper('\b'), isupper('\b'));
UT_ASSERT_EQ(ft_isupper(7), isupper(7));
