UT_ASSERT_EQ(ft_isblank('a'), isblank('a'));
UT_ASSERT_EQ(ft_isblank('a' + 0x100), isblank('a' + 0x100));
UT_ASSERT_EQ(ft_isblank('2'), isblank('2'));
UT_ASSERT_EQ(ft_isblank('Z'), isblank('Z'));
UT_ASSERT_EQ(ft_isblank('t'), isblank('t'));
UT_ASSERT_EQ(ft_isblank(0), isblank(0));
UT_ASSERT_EQ(ft_isblank(1), isblank(1));
UT_ASSERT_EQ(ft_isblank(9999), isblank(9999));
UT_ASSERT_EQ(ft_isblank('1'), isblank('1'));
UT_ASSERT_EQ(ft_isblank('2'), isblank('2'));
UT_ASSERT_EQ(ft_isblank('A'), isblank('A'));
UT_ASSERT_EQ(ft_isblank('Z'), isblank('Z'));
UT_ASSERT_EQ(ft_isblank(' '), isblank(' '));
UT_ASSERT_EQ(ft_isblank('%'), isblank('%'));
UT_ASSERT_EQ(ft_isblank('\t'), isblank('\t'));
UT_ASSERT_EQ(ft_isblank('\n'), isblank('\n'));
UT_ASSERT_EQ(ft_isblank('\v'), isblank('\v'));
UT_ASSERT_EQ(ft_isblank('\b'), isblank('\b'));
UT_ASSERT_EQ(ft_isblank(7), isblank(7));
