UT_ASSERT_EQ(ft_ispunct('a'), ispunct('a'));
UT_ASSERT_EQ(ft_ispunct('a' + 0x100), ispunct('a' + 0x100));
UT_ASSERT_EQ(ft_ispunct('2'), ispunct('2'));
UT_ASSERT_EQ(ft_ispunct('Z'), ispunct('Z'));
UT_ASSERT_EQ(ft_ispunct('t'), ispunct('t'));
UT_ASSERT_EQ(ft_ispunct(0), ispunct(0));
UT_ASSERT_EQ(ft_ispunct(1), ispunct(1));
UT_ASSERT_EQ(ft_ispunct(9999), ispunct(9999));
UT_ASSERT_EQ(ft_ispunct('1'), ispunct('1'));
UT_ASSERT_EQ(ft_ispunct('2'), ispunct('2'));
UT_ASSERT_EQ(ft_ispunct('A'), ispunct('A'));
UT_ASSERT_EQ(ft_ispunct('Z'), ispunct('Z'));
UT_ASSERT_EQ(ft_ispunct(' '), ispunct(' '));
UT_ASSERT_EQ(ft_ispunct('%'), ispunct('%'));
UT_ASSERT_EQ(ft_ispunct('\t'), ispunct('\t'));
UT_ASSERT_EQ(ft_ispunct('\n'), ispunct('\n'));
UT_ASSERT_EQ(ft_ispunct('\v'), ispunct('\v'));
UT_ASSERT_EQ(ft_ispunct('\b'), ispunct('\b'));
UT_ASSERT_EQ(ft_ispunct(7), ispunct(7));
